#!/bin/sh -e

# When the computer comes out of hibernate/suspend kill the old event client
# and start a new one.

EVENT_CLIENT=/usr/bin/xbmc_hama_mce

case "$1" in
    resume|thaw)
        if [ -x ${EVENT_CLIENT} ]; then
            killall -s SIGINT ${EVENT_CLIENT} || true
            sleep 2
            ${EVENT_CLIENT} &
        fi
    ;;
esac
