#!/bin/sh -e

# When the computer comes out of hibernate/suspend kill the old event client
# and start a new one.

EVENT_CLIENT=/usr/bin/xbmc_hama_mce
INITD_SCRIPT=/etc/init.d/xbmc_hama_mce

case "$1" in
    resume|thaw)
        if [ -x ${EVENT_CLIENT} ]; then
            ${INITD_SCRIPT} stop || true
            sleep 2
            ${INITD_SCRIPT} start
        fi
    ;;
esac
